### PR TITLE
Add support for fixit 2, required for Python 3.12.

### PR DESCRIPTION
**Pull request by sodul**
I left logic to support fixit 1 and 2 if desired but this can be easily updated to remove v1 support.

### CODE REVIEW

**Comment by sodul** [comment]
I see that the checks fail with python 3.7, which is no longer supported upstream. Should gray drop support for 3.7 and add a check for 3.12?

**Comment by dizballanze** [comment]
Hi! Yes, let's drop python3.7 (it's already eol anyway) and add python3.12.

**Comment by sodul** [comment]
All done. I've updated setup.py and the changelog so you can go ahead and do a new v0.14.0 release. Let me know if I missed anything.

If you are open to it I can take a look at updating the requirements to work with the latest versions of autoflake and rich, but that would be for a v0.15.0 release.

**Comment by dizballanze** [comment]
[0.14.0 released](https://pypi.org/project/gray/0.14.0/)
Thanks for the contribution!

**Pull request merged**
