### PR TITLE
Add isort options.

### PR DESCRIPTION
**Pull request by sodul**
This adds the following isort options:
* --isort-profile
* --isort-wrap-length
* --isort-multi-line-output
* --isort-known-third-party
* --isort-known-first-party
* --isort-known-local-folder
* --isort-skip-gitignore
* --isort-use-parentheses
* --isort-length-sort

The newer options do not override isort own defaults to help ensure profile consistency. The existing gray defaults stay the same.

Added unittests for the args.py module.
Fixed a bug in args.py where raising an `ArgumentError` was failing at runtime, replaced it with a `ValueError`.

### CODE REVIEW

**Comment by sodul** [comment]
Note that this PR is currently on top of #9, but can be split if need be, but that would be more work.

**Comment by dizballanze** [comment]
Can you please rebase on master?

**Comment by sodul** [comment]
> Can you please rebase on master?

Done

**Review by dizballanze — APPROVED** [review]

**Comment by dizballanze** [comment]
Thank you!
#9 and #10 were released in [v0.10.0](https://pypi.org/project/gray/0.10.0/)

**Comment by sodul** [comment]
@dizballanze 

Thank you for the prompt feedback and the new release.

Can you make v0.10.0 a GitHub release? That's partially required in order to use it properly with pre-commit configs since it pulls from GitHub and not from pypi.org.

https://github.com/dizballanze/gray/releases

Thanks!

**Comment by dizballanze** [comment]
> Can you make v0.10.0 a GitHub release? That's partially required in order to use it properly with pre-commit configs since it pulls from GitHub and not from pypi.org.


Done

**Pull request merged**
